version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  elasticsearch :
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node